import {readFileSync} from 'node:fs';
const s=JSON.parse(readFileSync(new URL('./concept.json',import.meta.url),'utf8'));
Object.assign(s,{eyebrow:'Маршрут · контроль городской дороги · iOS',tagline:'Ежедневный коридор по участкам: факт риска живёт до следующей проверки',insight:'городская дорога меняется быстрее общей карты: безопасный путь складывается из свежих фактов по конкретным участкам, а не из постов и разговоров',heroTitle:'Маршрут — знать каждый участок',heroDeck:'Сохраните ежедневный коридор, проверяйте его по участкам, фиксируйте риск и передавайте его в очередь следующей проверки.',deck:'Контроль ежедневного пути: коридор разбит на участки, каждый риск живёт до явной проверки и никогда не превращается в обсуждение.'});
s.tabs=[{id:'feed',label:'Путь',role:'corridor'},{id:'rides',label:'Проверки',role:'inspections'},{id:'music',label:'Маршруты',role:'routes'},{id:'profile',label:'Профиль',role:'profile'}];
s.positioning={mode:'differentiation',categoryFit:'Основная категория — Navigation: продукт хранит повторяемые дорожные коридоры и оперативное состояние их участков; социальные связи не являются отдельной лентой',familiarPatterns:['Сводка маршрута перед стартом','Карта участка с рисками','Контрольный проезд по расписанию','Профиль с личным вкладом'],distinctions:['Экран начинается с коридора и последовательности участков','Риск имеет срок жизни и явный статус проверки','Вместо обсуждения — три фиксированных результата','Live-режим публикует только неадресное состояние коридора'],evidenceScreens:['feed','post','compose','meetup','route','music']']};
s;s=s=s.product={audience:'Горожане 18–45 лет, которые почти ежедневно едут на велосипеде или самокате одним путём',situation:'Перед стартом нужно быстро понять состояние каждого участка привычной дороги',problem:'Общая карта обновляется медленно, а свободная лента смешивает факты разных районов и не показывает, какой участок уже перепроверен',promise:'За минуту до старта видно весь коридор: где путь свободен, где риск подтверждён и какой участок ждёт контроля',differentiator:'Базовая сущность — дорожный коридор, разбитый на участки; каждый риск имеет тип, координату, свежесть и очередь проверки',returnReasons:['Сводка коридора перед обычным временем старта','Новая проверка участка после погоды или ремонта','Погашение риска после контрольного проезда'],verticalSlice:{entry:'feed',action:'compose',result:'post'},coreLoop:['Открыть коридор и просмотреть участки по порядку движения','Зафиксировать структурированный риск на конкретном участке','Подтвердить, погасить или оставить риск в очереди проверки'],nonGoals:['Свободная социальная лента, комментарии и личная переписка','Адресные звонки, аудиокомнаты и разговорные каналы','Автомобильная навигация по всему городу и спортивные рейтинги'],world:{entities:[
{id:'corridor',name:'Коридор',identity:'стабильные начало, конец и порядок участков',fields:['название','длина','обычное время','статус пакета'],relations:[[{kind:'has-many',to:'segment'},{kind:'has-many',to:'inspection'}]},
{id:'segment',name:'Участок',identity:'границы внутри коридора и порядок движения',fields:['границы','длина','ориентир','статус'],relations:[{kind:'belongs-to',to:'corridor'},{kind:'has-many',to:'risk-fact'}]},
{id:'risk-fact',name:'Факт риска',identity:'участок, тип, координата, свежесть и срок жизни',fields:['тип','точка','свежесть','кадр','статус'],relations:[{kind:'belongs-to',to:'segment'},{kind:'has-many',to:'confirmation'}]},
{id:'confirmation',name:'Подтверждение',identity:'фиксированный результат контрольного проезда',fields:['проверено','неактуально','опасно','время'],relations:[{kind:'belongs-to',to:'risk-fact'}]},
{id:'inspection',name:'Контрольный проезд',identity:'коридор, время и участки',fields:['старт','участки','офлайн-пак','результат'],relations:[{kind:'belongs-to',to:'corridor'}]},
{id:'handoff',name:'Очередь проверки',identity:'факт и публичный статус необходимости контроля',fields:['нужна проверка','принято','закрыто'],relations:[{kind:'belongs-to',to:'risk-fact'}]},
{id:'rider',name:'Райдер',identity:'аккаунт, коридоры и вклад в проверки',fields:['имя','маршруты','проверенные участки','аварийная карточка'],relations:[{kind:'has-many',to:'corridor'}]},
{id:'credential',name:'Логин проката',identity:'домен и аккаунт',fields:['домен','логин','состояние'],relations:[]},{id:'ad',name:'Предложение сервиса',identity:'тип и близость к коридору',fields:['категория','расстояние','персонализация'],relations:[{kind:'belongs-to',to:'corridor'}]}],
actions:[
{id:'publish-fact',name:'Зафиксировать риск',actor:'rider',entity:'risk-fact',effect:'на участке появляется ограниченный по времени факт',screen:'compose',result:'коридор показывает риск в порядке движения',capabilities:['camera','photos','location']},
{id:'run-inspection',name:'Провести контрольный проезд',actor:'rider',entity:'inspection',effect:'статусы участков последовательно подтверждаются',screen:'meetup',result:'риск погашен, подтверждён или оставлен в очереди',capabilities:['calendar','push']},
{id:'publish-live-state',name:'Запустить live-состояние',actor:'rider',entity:'corridor',effect:'односторонний неадресный канал публикует статус участков без ответа',screen:'cast',result:'подписанные устройства получают только дорожную сводку',capabilities:['voip','mic','speech','audio']},
{id:'notify-corridor',name:'Обновить статус риска',actor:'rider',entity:'handoff',effect:'атомарное уведомление предлагает только фиксированные действия',screen:'route',result:'факт получает новый статус',javascript:['commnotif','remotenotif']},
{id:'sync-corridor',name:'Загрузить офлайн-пак',actor:':'rider',entity:'corridor',effect:'геометрия и риски доступны без сети',screen:'tv',result:'коридор готов без мобильной связи',Types:['wifiinfo','hotspot','fetch','bgtask']},
{id:'match-corridors',name:'Найти знакомые коридоры',actor:'rider',entity:'corridor',effect:'контакты локально сверяются с агрегированными маршрутами',screen:'friends',result:'видны коридоры без списка людей',capabilities:['contacts']},
{id:'protect-card',name:'Открыть аварийную карточку',actor:'rider',entity:'rider',effect:'данные раскрываются после биометрии',screen:'profile',result:'карточка доступна в аварии',capabilities:['faceid','keychain','appgroups']},
{id:'fill-rental',name:'Подставить логин проката',actor:'rider',entity:'credential',effect:'расширение заполняет форму',screen:'passwords',result:'прокат открывается без поиска пароля',capabilities:['autofill']},
{id:'personalize-offer',name:'Настроить предложения',actor:'rider',entity:'ad',effect:'IDFA используется только после согласия',screen:'ads',result:'показываются сервисы вдоль коридора',capabilities:['tracking']},
{id:'refresh-widget',name:'Обновить виджет',actor:'system',entity:'corridor',effect:'тихое уведомление меняет статус пути',screen:'notif',result:'риск виден до открытия',capabilities:['push','remotenotif']}]}};
s.backendless=[{needs:'Аккаунт, коридоры, участки, факты и проверки',solution:'Firebase Auth, Firestore и Storage через готовые SDK; своего серверного обработчика нет'},{needs:'Точный участок',solution:'Core Location, MapKit и локальная геометрия коридора'},{needs:'Одностороннее live-состояние',solution:'Управляемый publish-only transport без адресации и обратного медиаканала'},{needs:'Диктовка факта',solution:'AVAudioRecorder и SFSpeechRecognizer; аудио удаляется после локального разбора'},{needs:'Офлайн, фон и виджет',solution:'CoreData, FileManager, BGTaskScheduler и App Group'},{needs:'Атомарные статусы',solution:'Cloud Messaging и подписка на тему коридора; только фиксированные actions'},{needs:'Знакомые коридоры',solution:'Локальная сверка CNContactStore; адресная книга не выгружается'sites:
 [];
function setp(key,x){const p=s.permissions.find(p=>p.key===key);Object.assign(p,x);p.snack=p.fallback;p.reviewNote=`${p.feature}. Запрос или активация происходит только после жеста «${p.gesture}»; при отказе остаётся: ${p.fallback}.`}
setp('mic',{alert:{title:'«Маршрут» запрашивает доступ к микрофону',text:'Чтобы надиктовать дорожный факт и заполнить его поля.'},feature:'Диктовка типа риска и ориентира в структурированную карточку',gesture:'Надиктовать факт',screen:'cast',target:'cast',fallback:'Поля вводятся вручную',grounding:'AVAudioRecorder; локальный черновик удаляется после разбора'});
setp('speech',{alert:{title:'«Маршрут» запрашивает распознавание речи',text:'Чтобы превратить диктовку в поля факта.'},feature:'Локальное распознавание диктовки в поля дорожного факта',gesture:'Распознать поля',screen:'cast',target:'cast',fallback:'Черновик заполняется вручную',requires:'Микрофон разрешён и пользователь начал диктовку',grounding:'SFSpeechRecognizer; публикация только после проверки'});
setp('audio',{feature:'Короткие системные подсказки о ближайшем участке продолжают звучать в фоне',gesture:'Озвучивать риски в пути',screen:'cast',target:'background',fallback:'Подсказки видны на открытом экране',requires:'Активирован контрольный проезд',activate:true,grounding:'AVAudioSession playback воспроизводит синтезированные подсказки'});
setp('commnotif',{feature:'Атомарный статус коридора «Лёд у спуска» с действиями «Проверено» и «Неактуально»',gesture:'Опубликовать статус',screen:'route',target:'route',fallback:'Статус остаётся в сводке коридора',requires:'Подписка на коридор без конкретного получателя',activate:true,grounding:'Communication entitlement для структурированной карточки без текста ответа'});
setp('voip',{feature:'Односторонний неадресный live-канал агрегированного состояния коридора без выбранного получателя',gesture:'Запустить live-статус',screen:'meetup',target:'cast',fallback:'Состояние обновляется обычными push-событиями',requires:'Идёт проверка; обратного медиаканала и списка слушателей нет',activate:true,grounding:'PushKit transport поддерживает низколатентную доставку структурированных статусов'});
setp('calendar',{feature:'Контрольный проезд с коридором, участками и временем старта',gesture:'Добавить проверку в календарь',screen:'meetup',target:'invite',fallback:'Проверка остаётся в приложении'});
setp('contacts',{feature:'Локальная сверка адресной книги с агрегированными коридорами',gesture:'Найти знакомые коридоры',screen:'friends',target:'match',fallback:'Коридор можно найти по началу и концу',grounding:'CNContactStore; локально сравниваются хэши, адресная книга не выгружается'});
setp('push',{feature:'Предупреждения о высоком риске и времени контрольного проезда',gesture:'Включить оповещения',screen:'notif',target:'notif',fallback:'Изменения видны при открытии коридора'});
const meta={feed:['Состояние коридора','Показать участки и риски в порядке движения','Добавить факт'],post:['Факт риска','Показать доказательство и выбрать фиксированный результат','Подтвердить статус'],videos:['Визуальные разборы','Показать траекторию сложных участков','Открыть разбор'],compose:['Новый факт риска','Зафиксировать риск с участком, типом и сроком','Опубликовать факт'],rides:['Контрольные проезды','Планировать проверки участков','Запланировать проверку'],music:['Мои коридоры','Хранить повторяемые пути и офлайн-паки','Открыть коридор'],player:['Аудиогид участка','Прослушать системный разбор участка','Включить озвучивание'],background:['Маршрут в фоне','Показать ближайший риск на системном экране','Приостановить'],friends:['Знакомые коридоры','Найти совпадения путей локально','Найти коридоры'],match:['Найденные коридоры','Выбрать путь без раскрытия контактов','Сохранить коридор'],circles:['Очередь проверок','Показать участки, ожидающие контроля','Взять участок'],meetup:['Карточка проверки','Подготовить участки, время и live-состояние','Начать проверку'],route:['Результат проверки','Зафиксировать атомарный статус без адресата','Опубликовать статус'],cast:['Live-состояние коридора','Показывать неадресный статус и надиктовать факт','Надиктовать факт'],notif:['Оповещения коридора','Выбрать срочные риски и обновление виджета','Включить оповещения'],invite:['Проверка в календаре','Сохранить время и участки','Добавить в календарь']};
for(const sc of s.screens){const m=meta[sc.id];if(m){sc.title=m[0];sc.meta=m[1];sc.ui.purpose=m[1];sc.ui.primaryAction=m[2]}}
s.fixtures={note:'Свежие, устаревающие, офлайн и неподтверждённые состояния.',corridor:{title:'Дом — офис',distance:'7,4 км',usualDeparture:'08:10',segments:5},facts:[{title:'Лёд у спуска',segment:'Спуск к реке',freshness:'8 минут',state:'confirmed'},{title:'Песок после поворота',segment:'Набережная',freshness:'41 минута',state:'expiring'},{title:'Ремонт у моста',segment:'Мост — офис',freshness:'вчера',state:'needs-check'}]};
const ids=s.screens.map(x=>x.id);
s.prototypes=[{id:'all',hero:true,label:'Весь продукт',note:`${ids.length} экранов и ${s.permissions.length} доступ`,start:'phone',screens:ids,stops:[],authTarget:'feed'},{id:'corridor',label:'Коридор по участкам',note:'Сводка, факт и фиксированный результат',start:'feed',screens:['feed','post','compose','place','shoot','picker','route','notif','widget'],stops:['widget']},{id:'inspection',label:'Контрольный проезд',note:'План, календарь, очередь и live-состояние',start:'rides',screens:['rides','meetup','invite','circles','cast','background','route','feed'],stops:['feed']},{id:'offline',label:'Путь без сети',note:'Коридор, сеть, пакет и фон',start:'music',screens:['music','tv','background','videos','player','settings','widget'],stops:['widget']},{id:'discovery',label:'Знакомые коридоры',note:'Локальная сверка показывает пути, а не людей',start:'profile',screens:['profile','friends','match','music','lock'],stops:['lock']},{id:'extensions',label:'Виджет и прокаты',note:'App Group, Keychain и автозаполнение',start:'settings',screens:['settings','widget','feed','passwords','fill','ads','profile'],stops:['profile']},{id:'alerts',label:'Оповещения и приватность',note:'Риски, атомарные статусы и ATT',start:'notif',screens:['notif','route','widget','ads','settings','feed'],stops:['feed']}];
s.acceptance=[
{id:'publish-road-fact',name:'Зафиксировать риск',action:'publish-fact',given:'На спуске обнаружен лёд',when:'Выбраны участок, кадр и срок',then:'Факт появляется до опасной точки',screens:['feed','compose','place','shoot','picker','post'],capabilities:['location','camera','photos']},
{id:'prepare-offline-route',name:'Подготовить путь без сети',action:'sync-corridor',given:'Связь нестабильна',when:'Пак загружен в сети у старта',then:'Геометрия и риски доступны офлайн',screens:['music','tv','background'],capabilities:['wifiinfo','hotspot','fetch','bgtask']},
{id:'run-live-inspection',name:'Провести live-проверку',action:'publish-live-state',given:'После дождя проверяются три участка',when:'Запущен live-статус и надиктован факт',then:'Коридор получает статусы без адресного медиаканала',screens:['rides','meetup','cast','background'],capabilities:['voip','mic','speech','audio']},
{id:'publish-fixed-status',name:'Опубликовать результат',action:'notify-corridor',given:'Риск перепроверен',when:'Выбран фиксированный результат',then:'Подписка получает атомарный статус',screens:['post','route','notif','widget'],capabilities:['push','remotenotif','commnotif']},
{id:'shared-extensions',name:'Открыть путь и прокат',action:'fill-rental',given:'Расширения установлены',when:'Открыт виджет и выбран логин',then:'Сессия и логин доступны безопасно',screens:['settings','widget','passwords','fill'],capabilities:['appgroups','keychain','autofill']},
{id:'find-known-corridors',name:'Найти знакомые коридоры',action:'match-corridors',given:'Есть совпадающие пути',when:'Запущена локальная сверка',then:'Показаны коридоры без имён',screens:['friends','match','music'],capabilities:['contacts']},
{id:'schedule-inspection',name:'Запланировать проверку',action:'run-inspection',given:'Участок нужно проверить утром',when:'Плансь и время добавлены в календарь',then:'План сохранён',screens:['rides','meetup','invite'],capabilities:['calendar']},
{id:'open-emergency-card',name:'Открыть аварийную карточку',action:'protect-card',given:'Данные сохранены',when:'Подтверждён Face ID',then:'Карточка открыта или доступен код',screens:['profile','lock'],capabilities:['faceid']},
{id:'choose-ad-privacy',name:'Выбрать режим предложений',action:'personalize-offer',given:'Показаны сервисы вдоль пути',when:'Принято решение ATT',then:'Отказ не отключает функции',screens:['settings','ads','profile'],capabilities:['tracking']}];
s.appStore.name='Маршрут — контроль пути';s.appStore.subtitle='Статус каждого участка';s.appStore.promo='Проверьте ежедневный коридор до старта, отметьте риск и закройте его результатом контрольного проезда.';s.appStore.keywords='велосипед,самокат,дорога,риск,участок,маршрут,офлайн,проверка,безопасность';s.appStore.category={primary:'Navigation',secondary:'Utilities'};s.appStore.ageRating='4+';s.appStore.description=['«Маршрут» превращает привычную дорогу в коридор из участков. Перед стартом видно, где путь свободен, где риск подтверждён и что нужно перепроверить.','КОРИДОР ПО УЧАСТКАМ\nРиски стоят в порядке движения и имеют свежесть, координату и срок жизни.','КОНТРОЛЬНЫЙ ПРОЕЗД\nВыберите участки после дождя или ремонта и закройте каждый фиксированным результатом.','ФАКТ БЕЗ ОБСУЖДЕНИЯ\nКадр и ориентир доказывают состояние дороги. Доступны только фиксированные статусы.','ОФЛАЙН ДО СТАРТА\nЗагрузите геометрию, факты и разборы. Виджет покажет ближайший риск.'];s.appStore.whatsNew='Первая версия: коридоры, факты риска, контрольные проезды, офлайн-паки и виджет.';s.appStore.assets.screens=[{screen:'feed',headline:'Знайте путь до старта',body:'Все участки и риски стоят по порядку движения'},{screen:'compose',headline:'Фиксируйте точный факт',body:'Участок, тип и срок жизни без обсуждения'},{screen:'rides',headline:'Проверяйте после изменений',body:'Контрольный проезд закрывает каждый риск результатом'},{screen:'route',headline:'Публикуйте только статус globe', IRequest:'Проверено, неактуально или нужна новая проверка'},{screen:'music',headline:'Маршрут готов офлайн',body:'Геометрия, риски и разборы доступны без сети'}];
process.stdout.write(JSON.stringify(s,null,2)+'\n');
