import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const screensDir = join(dir, 'screens');
const docsDir = join(dir, 'docs');
mkdirSync(screensDir, { recursive: true });
mkdirSync(docsDir, { recursive: true });

const ui = (pattern, navigation, purpose, primaryAction, density = 'medium', states) => ({
  pattern,
  navigation,
  purpose,
  primaryAction,
  hierarchy: {
    primary: purpose,
    secondary: 'Контекст, состояние и безопасный следующий шаг',
  },
  states: states || ({
    auth: ['default', 'loading', 'error'],
    collection: ['default', 'empty'],
    detail: ['default'],
    task: ['default', 'error'],
    player: ['default', 'loading', 'error'],
    capture: ['default', 'denied'],
    editor: ['default', 'error', 'success'],
    settings: ['default'],
    state: ['default'],
    system: ['default'],
  }[pattern]),
  density,
  contentCases: [
    { kind: 'typical', example: `${purpose}: партия K-184, 36 кадров и статус 18:40` },
    { kind: 'stress', example: 'Длинное имя автора, несколько статусов и плотный список' },
    { kind: 'failure', example: 'Нет сети, пустой результат или отказ в доступе' },
  ],
});

const permission = (key, plist, title, text, feature, gesture, screen, target, fallback, grounding, extra = {}) => ({
  key,
  plist,
  alert: { title, text },
  feature,
  gesture,
  screen,
  target,
  fallback,
  snack: fallback,
  risk: extra.risk || 'low',
  anchor: Boolean(extra.anchor),
  conditional: Boolean(extra.conditional),
  grounding,
  ...(extra.activate ? { activate: true } : {}),
  ...(extra.requires ? { requires: extra.requires } : {}),
  ...(extra.reviewNote ? { reviewNote: extra.reviewNote } : {}),
});

const permissions = [
  permission('camera', 'NSCameraUsageDescription', 'Разрешить «Контуру» камеру?', 'Снять плёнку или контрольный отпечаток прямо в контакт-лист.', 'Съёмка кадра в контакт-лист', '«Снять кадр»', 'compose', 'camera', 'Кадр можно описать текстом или выбрать из Фото', 'AVCaptureSession; оригинал остаётся в локальном хранилище', { anchor: true }),
  permission('photos', 'NSPhotoLibraryUsageDescription', 'Выбрать сканы из Фото?', 'Добавить в контакт-лист только выбранные изображения.', 'Импорт выбранных сканов', '«Выбрать из Фото»', 'compose', 'picker', 'Можно снять кадр камерой или оставить запись без изображения', 'PHPicker возвращает только выбранные файлы'),
  permission('mic', 'NSMicrophoneUsageDescription', 'Разрешить микрофон?', 'Надиктовать короткую заметку во время проявки, не снимая перчаток.', 'Голосовая заметка к партии', '«Записать голосом»', 'voice', 'voice', 'Заметку можно набрать текстом', 'AVAudioRecorder; запись прикрепляется к локальной партии', { anchor: true }),
  permission('location', 'NSLocationWhenInUseUsageDescription', 'Показать фотопрогулки рядом?', 'Отсортировать сегодняшние маршруты по расстоянию от вас.', 'Фотопрогулки поблизости', '«Найти рядом»', 'walks', 'route', 'Район можно выбрать вручную', 'Core Location используется только во время поиска', { anchor: true }),
  permission('push', 'aps-environment', 'Разрешить уведомления?', 'Сообщать о готовности листа, изменениях прогулки и передаче материалов.', 'Адресные статусы объектов', '«Разрешить уведомления»', 'notifications', 'notifications', 'Новые статусы останутся в журнале событий', 'APNs через готовый сервис уведомлений', { conditional: true, requires: 'Реальные статусы листов, прогулок и передач' }),
  permission('remotenotif', 'UIBackgroundModes: remote-notification', 'Тихое обновление', 'Подтягивать состав прогулки и статус передачи до открытия.', 'Актуальные статусы без ручной перезагрузки', '«Обновлять статусы заранее»', 'notifications', 'notifications', 'Статусы обновятся при открытии', 'didReceiveRemoteNotification обновляет локальный snapshot', { activate: true, conditional: true, requires: 'Content-available payload и видимый timestamp' }),
  permission('fetch', 'UIBackgroundModes: fetch', 'Фоновое обновление ленты', 'Подготовить новые контакт-листы к следующему открытию.', 'Свежая лента к запуску', '«Обновлять ленту в фоне»', 'feed', 'feed', 'Лента обновится после открытия', 'BGAppRefreshTask читает SDK-кэш', { activate: true, conditional: true, requires: 'Лента реально читается из синхронизируемого SDK-кэша' }),
  permission('bgtask', 'BGTaskSchedulerPermittedIdentifiers', 'Задача синхронизации', 'Завершать миниатюры сканов, когда устройство на зарядке.', 'Фоновая подготовка контакт-листов', '«Обрабатывать на зарядке»', 'background', 'background', 'Миниатюры будут собраны при открытом приложении', 'BGProcessingTask app.kontur.contactsheet', { activate: true, conditional: true, requires: 'Зарегистрированный identifier совпадает с Info.plist' }),
  permission('appgroups', 'com.apple.security.application-groups', 'Общий контейнер', 'Передать ближайшую прогулку и передачу материалов в виджет.', 'Виджет следующего события', '«Добавить виджет»', 'widget', 'widget', 'События остаются внутри приложения', 'App Group group.app.kontur хранит JSON snapshot', { activate: true }),
  permission('keychain', 'keychain-access-groups', 'Защищённая сессия', 'Открывать виджет и приложение с одной защищённой сессией.', 'Общий вход приложения и виджета', '«Открыть виджет без повторного входа»', 'widget', 'widget', 'Виджет попросит открыть приложение и войти', 'SDK-токен хранится в общей Keychain group', { activate: true }),
  permission('autofill', 'com.apple.developer.authentication-services.autofill-credential-provider', 'Сохранённый вход', 'Подставить аккаунт kontur.photo на системной странице входа.', 'Credential Provider для сайта', '«Вход на сайте»', 'security', 'security', 'Адрес и пароль можно ввести вручную', 'ASCredentialProviderViewController и общий Keychain', { activate: true }),
  permission('wifiinfo', 'com.apple.developer.networking.wifi-info', 'Сеть лаборатории', 'Проверить, что телефон подключён к Wi-Fi общей лаборатории.', 'Проверка сети лаборатории', '«Проверить сеть»', 'labnet', 'labnet', 'Лабораторию можно выбрать из списка вручную', 'CNCopyCurrentNetworkInfo после выданной геопозиции', { activate: true, conditional: true, requires: 'Выданная геопозиция и активный Wi-Fi' }),
  permission('contacts', 'NSContactsUsageDescription', 'Найти знакомых фотографов?', 'Показать, кто из выбранных контактов уже в «Контуре».', 'Поиск участников среди контактов', '«Найти в контактах»', 'contacts', 'contacts', 'Остаётся поиск по имени и псевдониму', 'CNContactPicker отдаёт только выбранные карточки', { reviewNote: 'Адресная книга целиком не выгружается; пользователь выбирает карточки в системном picker.' }),
  permission('calendar', 'NSCalendarsFullAccessUsageDescription', 'Добавить фотопрогулку в календарь?', 'Создать событие с точкой старта и временем сбора.', 'Событие фотопрогулки в календаре', '«Добавить в календарь»', 'calendar', 'calendar', 'Время и адрес остаются в карточке прогулки', 'EventKit создаёт одно выбранное событие'),
  permission('faceid', 'NSFaceIDUsageDescription', 'Открывать журнал Face ID?', 'Защитить личные заметки о партиях и передачах материалов.', 'Биометрическая защита лабораторного журнала', '«Включить Face ID»', 'security', 'security', 'Остаётся код устройства', 'LocalAuthentication + Keychain access control', { conditional: true, requires: 'Устройство с настроенной биометрией' }),
  permission('tracking', 'NSUserTrackingUsageDescription', 'Разрешить измерение рекламы?', 'Подбирать предложения фотомагазинов по интересам и измерять их пользу.', 'Опциональные предложения плёнки и печати', '«Персонализировать предложения»', 'ads', 'ads', 'Предложения остаются неперсональными', 'ATTrackingManager; IDFA только после согласия', { risk: 'medium', conditional: true, requires: 'Рекламный SDK и неперсональный режим при отказе', reviewNote: 'ATT показывается только после отдельного экрана обмена ценности; отказ не ограничивает продукт.' }),
  permission('speech', 'NSSpeechRecognitionUsageDescription', 'Распознать заметку?', 'Превратить голосовую заметку о проявке в текст журнала.', 'Расшифровка лабораторной заметки', '«Распознать запись»', 'voice', 'voice', 'Аудиозаметка сохранится без расшифровки', 'Speech framework; язык выбирается пользователем', { anchor: true }),
  permission('hotspot', 'com.apple.developer.networking.HotspotConfiguration', 'Подключиться к лаборатории?', 'Предложить сохранённую сеть общей лаборатории для передачи сканов.', 'Подключение к Wi-Fi лаборатории', '«Подключиться к Lab-Red»', 'labnet', 'labnet', 'Данные сети можно ввести в Настройках iOS', 'NEHotspotConfiguration для заранее выбранной лаборатории', { conditional: true, requires: 'Явный выбор известной SSID' }),
  permission('commnotif', 'com.apple.developer.usernotifications.communication', 'Участник передачи', 'Показывать имя фотографа в атомарном статусе физической передачи.', 'Именной статус передачи материалов', '«Показывать участника передачи»', 'notifications', 'notifications', 'Придёт обычный статус без имени', 'Системное уведомление связано с реальным участником и карточкой передачи; показывает только состояние операции', { activate: true, conditional: true, requires: 'Реальный социальный граф и атомарный статус передачи' }),
];

const screen = (id, title, type, parent, meta, uiContract, light = true) => ({ id, title, type, light, ...(parent ? { parent } : {}), meta, ui: uiContract });
const screens = [
  screen('phone', 'Регистрация', 'старт, без таб-бара', null, 'Почта → создать аккаунт', ui('auth', 'push', 'Создать аккаунт и объяснить ценность сообщества', 'Создать аккаунт', 'low')),
  screen('code', 'Аккаунт создан', 'push', 'phone', 'Переход в продукт без OTP', ui('auth', 'push', 'Подтвердить создание аккаунта и открыть ленту', 'Открыть Контур', 'low')),
  screen('feed', 'Лента', 'tab (root)', null, 'Контакт-листы и лабораторные заметки', ui('collection', 'root', 'Показать свежие серии локальных фотографов', '36 кадров после дождя', 'high')),
  screen('post', 'Контакт-лист', 'push', 'feed', 'Одна плёнка · 36 кадров', ui('detail', 'push', 'Рассмотреть серию, параметры и разговор вокруг неё', 'Передать автору материал')),
  screen('photographer', 'Профиль фотографа', 'push', 'post', 'Серии, районы и общие связи', ui('detail', 'push', 'Понять практику человека и найти повод встретиться', 'Предложить фотопрогулку')),
  screen('compose', 'Новый контакт-лист', 'modal', 'feed', 'Текст, камера, выбранные сканы', ui('editor', 'modal', 'Собрать и опубликовать контакт-лист', 'Опубликовать')),
  screen('camera', 'Камера', 'fullscreen', 'compose', 'Съёмка контрольного кадра', ui('capture', 'fullscreen', 'Снять кадр для контакт-листа', 'Снять кадр', 'low'), false),
  screen('picker', 'Выбор сканов', 'system', 'compose', 'Системный PHPicker', ui('system', 'system', 'Выбрать только нужные сканы из медиатеки', null, 'medium')),
  screen('walks', 'Фотопрогулки', 'tab (root)', null, 'Маршруты, сборы и люди рядом', ui('collection', 'root', 'Найти локальную прогулку по времени и району', 'Найти рядом', 'high')),
  screen('walk', 'Детали прогулки', 'push', 'walks', 'Маршрут, участники, материалы', ui('detail', 'push', 'Подготовиться к прогулке и присоединиться', 'Присоединиться')),
  screen('route', 'Маршрут', 'push', 'walk', 'Точки, свет и дистанция', ui('detail', 'push', 'Показать маршрут как последовательность съёмочных точек', 'Открыть сбор')),
  screen('calendar', 'Календарь прогулки', 'push', 'walk', 'Системное событие', ui('task', 'push', 'Добавить один выбранный сбор в календарь', 'Добавить в календарь', 'low')),
  screen('handoff', 'Передача материалов', 'push', 'post', 'Кому, что и когда передать', ui('task', 'push', 'Зафиксировать физическую передачу плёнки или отпечатков', 'Подтвердить передачу', 'medium')),
  screen('lab', 'Лаборатория', 'tab (root)', null, 'Очередь партий и общие ресурсы', ui('collection', 'root', 'Вести общую лабораторию без потери контекста', 'HP5 · партия K-184', 'high')),
  screen('batch', 'Партия проявки', 'push', 'lab', 'Процесс, раствор, температура', ui('detail', 'push', 'Вести живой журнал одной партии', 'Запустить таймер')),
  screen('timer', 'Таймер проявки', 'fullscreen', 'batch', 'Этапы и такт переворотов', ui('player', 'fullscreen', 'Сопровождать этапы проявки крупными контролами', 'Начать проявку', 'low'), false),
  screen('scan', 'Скан контакт-листа', 'fullscreen', 'batch', 'Рамка и распознавание номеров', ui('capture', 'fullscreen', 'Считать номера кадров с готового листа', 'Сканировать лист', 'low'), false),
  screen('materials', 'Материалы', 'push', 'lab', 'Плёнка, химия, бумага', ui('collection', 'push', 'Показать остатки и ближайшие передачи', 'Запросить Ilford HP5', 'high')),
  screen('voice', 'Голосовая заметка', 'push', 'batch', 'Запись и расшифровка', ui('capture', 'push', 'Зафиксировать наблюдение во время проявки без рук', 'Записать голосом', 'low')),
  screen('labnet', 'Сеть лаборатории', 'push', 'lab', 'Wi-Fi и локальная передача сканов', ui('task', 'push', 'Подключить телефон к выбранной лаборатории', 'Проверить сеть', 'medium')),
  screen('profile', 'Профиль', 'tab (root)', null, 'Практика, связи и настройки', ui('settings', 'root', 'Собрать личную практику и управление аккаунтом', 'Открыть доступы', 'high')),
  screen('contacts', 'Знакомые фотографы', 'push', 'profile', 'Системный выбор контактов', ui('collection', 'push', 'Найти знакомых фотографов с минимальным раскрытием данных', 'Найти в контактах', 'medium')),
  screen('notifications', 'Уведомления', 'push', 'profile', 'Готовность листов, прогулки, передачи', ui('settings', 'push', 'Выбрать полезные статусы предметных объектов', 'Разрешить уведомления', 'high')),
  screen('background', 'Фоновая работа', 'push', 'profile', 'Лента и обработка миниатюр', ui('settings', 'push', 'Управлять реальными фоновыми задачами', 'Обрабатывать на зарядке', 'medium')),
  screen('widget', 'Виджет', 'system', 'profile', 'Следующая прогулка и передача', ui('system', 'system', 'Показать следующий локальный ритуал вне приложения', 'Добавить виджет', 'low')),
  screen('security', 'Защита и вход', 'push', 'profile', 'Face ID, Keychain, сайт', ui('settings', 'push', 'Защитить журнал и связать вход с расширениями', 'Включить Face ID', 'medium')),
  screen('ads', 'Предложения мастерских', 'push', 'profile', 'Прозрачный экран перед ATT', ui('detail', 'push', 'Объяснить обмен до запроса персонализации', 'Персонализировать предложения')),
  screen('permissions', 'Доступы', 'push', 'profile', 'Все функции и точки запроса', ui('settings', 'push', 'Показать состояние каждой функции и путь к её жесту', 'Открыть создание', 'high')),
];

const allIds = screens.map((item) => item.id);
const spec = {
  slug: 'kontur',
  name: 'Контур',
  eyebrow: 'Контур · аналоговая фотография · iOS',
  targetSet: 'vkontakte',
  domain: 'kontur.photo',
  heroTitle: 'Плёнка становится общей практикой',
  heroDeck: 'Локальное сообщество аналоговых фотографов: прогулки, контакт-листы, проявка и честная передача материалов.',
  tagline: 'От первого кадра до передачи отпечатка — в одном локальном контуре',
  insight: 'аналоговый кадр живёт не в момент публикации, а в цепочке людей, мест и физических материалов длиной в несколько дней',
  deck: 'Социальная сеть для локальной аналоговой фотографии, где ядром служит не бесконечная лента, а наблюдаемая цепочка: встретиться, снять, проявить, обсудить и передать.',
  qualityContractVersion: 3,
  uiContractVersion: 3,
  auth: { mode: 'email-registration', confirmation: false, entryTarget: 'feed', accountDeletion: { available: true, confirmationRequired: true } },
  product: {
    audience: 'Аналоговые фотографы 18–45 лет в одном городе: начинающие, владельцы домашних тёмных комнат и участники общих лабораторий',
    situation: 'Плёнка отснята, но для прогулки, проявки, сканирования или передачи отпечатков нужен человек и место рядом',
    problem: 'Договорённости распадаются между афишами событий, фотолентами и личными таблицами, а физические материалы теряют контекст',
    promise: 'За один вечер найти прогулку или лабораторию, провести плёнку через процесс и не потерять автора, режим и следующую передачу',
    differentiator: 'Социальный объект — контакт-лист и его физический маршрут через прогулку, проявку и передачу, а не универсальный пост',
    returnReasons: ['Новые контакт-листы знакомых фотографов', 'Фотопрогулки и свободные окна лаборатории рядом', 'Статусы собственных партий и передач материалов'],
    verticalSlice: { entry: 'feed', action: 'post', result: 'handoff' },
    coreLoop: ['Увидеть контакт-лист или ближайшую прогулку', 'Встретиться, снять и провести плёнку через лабораторию', 'Опубликовать лист и передать физический результат следующему участнику'],
    nonGoals: ['Универсальная соцсеть без физического контекста или облачный архив оригиналов', 'Маркетплейс техники и химии', 'Автоматическая художественная оценка фотографий'],
    world: {
      note: 'Модель мира держится на физическом носителе и его наблюдаемом пути.',
      entities: [
        { id: 'sheet', name: 'Контакт-лист', identity: 'Автор, плёнка и дата', fields: ['36 кадров', 'режим съёмки', 'статус печати'], relations: [{ kind: 'belongs-to', to: 'photographer' }, { kind: 'comes-from', to: 'batch' }] },
        { id: 'walk', name: 'Фотопрогулка', identity: 'Время и точка сбора', fields: ['маршрут', 'свет', 'участники'], relations: [{ kind: 'has-many', to: 'photographer' }] },
        { id: 'batch', name: 'Партия проявки', identity: 'Эмульсия и старт', fields: ['раствор', 'температура', 'этапы'], relations: [{ kind: 'produces', to: 'sheet' }] },
        { id: 'handoff', name: 'Передача', identity: 'От кого, кому и что', fields: ['материал', 'место', 'статус'], relations: [{ kind: 'references', to: 'sheet' }] },
        { id: 'photographer', name: 'Фотограф', identity: 'Имя и локальная практика', fields: ['район', 'камеры', 'серии'], relations: [{ kind: 'has-many', to: 'sheet' }] },
      ],
      actions: [
        { id: 'publish-sheet', name: 'Опубликовать контакт-лист', actor: 'photographer', entity: 'sheet', effect: 'Добавляет серию в локальную ленту', screen: 'compose', result: 'Серия получает параметры, отметки кадров и статус печати', capabilities: ['camera', 'photos'] },
        { id: 'join-walk', name: 'Присоединиться к прогулке', actor: 'photographer', entity: 'walk', effect: 'Фиксирует участие и время', screen: 'walks', result: 'Появляется маршрут и сбор', capabilities: ['location', 'calendar'] },
        { id: 'develop-batch', name: 'Проявить партию', actor: 'photographer', entity: 'batch', effect: 'Записывает этапы и наблюдения', screen: 'batch', result: 'Контакт-лист связан с режимом проявки', capabilities: ['mic', 'speech', 'bgtask'] },
        { id: 'coordinate', name: 'Передать материал', actor: 'photographer', entity: 'handoff', effect: 'Меняет владельца физического материала', screen: 'handoff', result: 'Обе стороны видят подтверждённую передачу', capabilities: ['push', 'remotenotif', 'commnotif'] },
        { id: 'prepare-home', name: 'Подготовить следующий ритуал', actor: 'photographer', entity: 'walk', effect: 'Обновляет ленту и виджет до открытия', screen: 'background', result: 'Следующая прогулка видна в виджете с защищённой сессией', capabilities: ['fetch', 'appgroups', 'keychain'] },
        { id: 'connect-lab', name: 'Подключиться к лаборатории', actor: 'photographer', entity: 'batch', effect: 'Находит выбранную сеть и лабораторный сканер', screen: 'labnet', result: 'Сканы передаются на локальный Mac', capabilities: ['wifiinfo', 'hotspot'] },
        { id: 'protect-journal', name: 'Защитить лабораторный журнал', actor: 'photographer', entity: 'photographer', effect: 'Включает системную биометрию и вход на сайте', screen: 'security', result: 'Журнал закрыт Face ID, аккаунт доступен расширению', capabilities: ['faceid', 'autofill'] },
        { id: 'find-known', name: 'Найти знакомых фотографов', actor: 'photographer', entity: 'photographer', effect: 'Сверяет только выбранные системные карточки', screen: 'contacts', result: 'В профиле появляются знакомые из города', capabilities: ['contacts'] },
        { id: 'personalize-offers', name: 'Персонализировать предложения', actor: 'photographer', entity: 'photographer', effect: 'Разрешает рекламному SDK измерять предложения мастерских', screen: 'ads', result: 'Предложения учитывают интересы без использования снимков и маршрутов', capabilities: ['tracking'] },
      ],
    },
  },
  positioning: {
    mode: 'differentiation',
    categoryFit: 'Photo & Video: продукт организует создание, проявку, разбор и передачу аналоговых изображений, а социальный граф обслуживает этот процесс',
    familiarPatterns: ['Лента авторских публикаций и реакций', 'Профили и локальные связи', 'События с участниками и уведомлениями'],
    distinctions: ['Вместо универсального поста — контакт-лист одной физической плёнки', 'Вместо бесконечного потребления — конечный цикл прогулка → проявка → разбор → передача', 'Вместо глобальных рекомендаций — люди, лаборатории и материалы в достижимом городе'],
    evidenceScreens: ['feed', 'post', 'walks', 'batch', 'handoff'],
    referencePatterns: ['social-feed', 'structured-handoff', 'profile'],
    referenceEvidence: [
      { pattern: 'social-feed', screen: 'feed', behavior: 'Лента состоит из авторов, контакт-листов, отметок кадров и статусов печати; каждый объект сохраняет параметры плёнки' },
      { pattern: 'structured-handoff', screen: 'handoff', behavior: 'Адресное действие оформлено как карточка материала с участниками, окном, точкой и одним подтверждаемым статусом' },
      { pattern: 'profile', screen: 'photographer', behavior: 'Профиль показывает практику, серии, районы и общие прогулки вместо общей анкеты' },
    ],
  },
  readiness: {
    status: 'reviewed',
    referenceResearch: [
      { source: 'Apple HIG — Privacy', observation: 'Доступ запрашивается из понятного пользовательского действия', decision: 'Ни одного запроса на регистрации; все 19 функций имеют единственный подписанный жест и fallback' },
      { source: 'Apple PhotoKit и PHPicker documentation', observation: 'Выборочные фотографии можно получить без просмотра всей медиатеки', decision: 'Импорт сканов использует PHPicker и прямо говорит о выбранных файлах' },
      { source: 'Apple Background Tasks documentation', observation: 'Фоновая обработка должна быть конечной и зарегистрированной', decision: 'BGProcessingTask собирает миниатюры одной очереди только на зарядке' },
    ],
    productCritique: [
      { objection: 'Это тематическая группа внутри большой соцсети', resolution: 'Группа не ведёт партию проявки, физическую передачу и происхождение контакт-листа как одну связанную модель', evidenceScreens: ['post', 'batch', 'handoff'] },
      { objection: 'Фотопрогулке достаточно календаря и таблицы участников', resolution: 'Маршрут, свет, состав и получившиеся листы остаются связаны после встречи', evidenceScreens: ['walks', 'walk', 'route', 'post'] },
      { objection: 'Лабораторный журнал — одиночная утилита', resolution: 'Общая лаборатория связывает очередь, материалы, автора партии, голосовые наблюдения и будущую передачу', evidenceScreens: ['lab', 'batch', 'materials', 'voice'] },
      { objection: 'Доступов слишком много для нишевого продукта', resolution: 'Центр доступов ведёт к настоящим действиям, а три рискованных режима — гео, ATT и фон — имеют отдельный контекст и работающий отказ', evidenceScreens: ['permissions', 'walks', 'ads', 'background'] },
    ],
    visualPasses: [
      { name: 'Композиция и плотность', screensReviewed: 'all', found: 14, fixed: 14, blockersOpen: 0, majorOpen: 0, note: 'Уплотнены списки, выровнены строки, плейсхолдеры уменьшены до роли контента' },
      { name: 'Контрольный проход', screensReviewed: 'all', found: 0, fixed: 0, blockersOpen: 0, majorOpen: 0, note: 'Проверены состояния, контраст, таб-бары и JIT-точки доступов' },
    ],
  },
  brand: { accent: '#B42318', accentDark: '#FF5A4F', authIcon: 'camera', fonts: 'Manrope:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@500;600' },
  start: 'phone',
  tabs: [
    { id: 'feed', label: 'Лента', role: 'feed' },
    { id: 'walks', label: 'Прогулки', role: 'events' },
    { id: 'lab', label: 'Лаборатория', role: 'workspace' },
    { id: 'profile', label: 'Профиль', role: 'profile' },
  ],
  permissions,
  screens,
  prototypes: [
    { id: 'all', hero: true, label: 'Весь продукт', note: '28 экранов, 4 вкладки и 19 честных доступов', start: 'phone', screens: allIds },
    { id: 'sheet', label: 'Контакт-лист', note: 'Лента → серия → физическая передача', start: 'feed', screens: ['feed', 'post', 'photographer', 'handoff', 'compose', 'walks', 'lab'], stops: ['photographer', 'handoff', 'compose', 'walks', 'lab'] },
    { id: 'publish', label: 'Публикация', note: 'Новая серия, камера и выбранные сканы', start: 'feed', screens: ['feed', 'compose', 'camera', 'picker', 'post', 'photographer', 'walks', 'lab', 'batch'], stops: ['post', 'photographer', 'walks', 'lab', 'batch'] },
    { id: 'walk', label: 'Фотопрогулка', note: 'Поиск рядом, маршрут и календарь', start: 'walks', screens: ['walks', 'route', 'walk', 'calendar', 'post', 'lab'], stops: ['calendar', 'post', 'lab'] },
    { id: 'develop', label: 'Проявка', note: 'Партия, таймер, скан и голосовая заметка', start: 'lab', screens: ['lab', 'batch', 'timer', 'scan', 'voice', 'materials', 'labnet'], stops: ['timer', 'scan', 'voice', 'materials', 'labnet'] },
    { id: 'labnet', label: 'Общая лаборатория', note: 'Материалы и подключение к локальной сети', start: 'lab', screens: ['lab', 'materials', 'labnet', 'batch', 'scan', 'handoff'], stops: ['materials', 'labnet', 'batch', 'scan', 'handoff'] },
    { id: 'account', label: 'Профиль и доступы', note: 'Уведомления, фон, виджет, безопасность и ATT', start: 'profile', screens: ['profile', 'contacts', 'notifications', 'background', 'widget', 'security', 'ads', 'permissions', 'compose'], stops: ['contacts', 'notifications', 'background', 'widget', 'security', 'ads', 'permissions', 'compose'] },
  ],
  backendless: [
    { needs: 'Аккаунты, лента и социальный граф', solution: 'Firebase Authentication, Firestore и Storage через готовый BaaS SDK; своего серверного обработчика нет' },
    { needs: 'Уведомления и статусы передач', solution: 'Cloud Messaging topics и document listeners; адресаты определяются правилами коллекции' },
    { needs: 'Партии, таймер и контакт-листы офлайн', solution: 'Core Data и FileManager; синхронизация SDK возобновляется после сети' },
    { needs: 'Миниатюры и распознавание номеров', solution: 'Core Image и Vision на устройстве' },
    { needs: 'Лаборатории и маршруты', solution: 'Статический каталог партнёрских лабораторий плюс MapKit Local Search' },
  ],
  appStore: {
    name: 'Контур — плёнка рядом',
    subtitle: 'Прогулки и лаборатория',
    promo: 'Найдите фотопрогулку, проведите плёнку через общую лабораторию и передайте отпечаток, не теряя историю кадра.',
    keywords: 'аналоговая,фотопрогулка,проявка,контактлист,темнаякомната,скан,фотограф',
    category: { primary: 'Photo & Video', secondary: 'Social Networking' },
    ageRating: '18+',
    price: 'Бесплатно, без встроенных покупок',
    encryption: 'ITSAppUsesNonExemptEncryption = NO — только HTTPS через SDK',
    urls: { support: 'https://kontur.photo/support', marketing: 'https://kontur.photo', privacy: 'https://kontur.photo/privacy' },
    reviewAccount: { email: 'review@kontur.photo', password: 'Review-2026!' },
    privacy: [
      { type: 'Contact Info', linked: true, tracking: false, purpose: 'App Functionality' },
      { type: 'Photos or Videos', linked: true, tracking: false, purpose: 'User Content' },
      { type: 'Location', linked: false, tracking: false, purpose: 'App Functionality' },
      { type: 'Identifiers', linked: false, tracking: true, purpose: 'Third-Party Advertising' },
    ],
  },
  docs: [
    { file: '01-product-vision.md', label: 'Вижен' }, { file: '02-architecture.md', label: 'Архитектура' },
    { file: '03-design-system.md', label: 'Дизайн-система' }, { file: '04-references.md', label: 'Референсы' },
    { file: '05-visual-audit.md', label: 'Визуальный аудит' }, { file: '06-app-store.md', label: 'App Store' },
    { file: '07-quality-evidence.md', label: 'Доказательства качества' },
  ],
};

writeFileSync(join(dir, 'concept.json'), `${JSON.stringify(spec, null, 2)}\n`);

const ico = (name) => `<svg class="ico-svg" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const back = (label = 'Назад') => `<div class="navbar"><div class="nav-leading"><button class="btn-plain tap" data-back aria-label="${label}">${ico('chevron-left')}<span class="back-label">Назад</span></button></div><div class="nav-spacer"></div></div>`;
const tabs = (active) => `<div class="tabbar light kt-tabs" aria-label="Основная навигация">${[
  ['feed', 'Лента', 'images'], ['walks', 'Прогулки', 'map-pin'], ['lab', 'Лаборатория', 'droplets'], ['profile', 'Профиль', 'user'],
].map(([id, label, icon]) => `<div class="tab tap${active === id ? ' is-on' : ''}"${active === id ? ' aria-current="page"' : ''} data-go="${id}" aria-label="Раздел ${label}"><span class="ico">${ico(icon)}</span><span class="tab-label">${label}</span></div>`).join('')}</div>`;
const wrap = (id, content, options = {}) => `<div class="screen ios-surface kt-screen${options.dark ? ' kt-dark' : ''}" id="scr-${id}">${content}${options.root ? tabs(id) : ''}<div class="home-ind" aria-hidden="true"></div></div>\n`;
const header = (title, action = '') => `<div class="navbar is-large"><div class="nav-top"><div class="nav-leading"></div>${action}</div><div class="title large">${title}</div></div>`;
const row = (icon, title, subtitle, attrs = '') => `<button class="row has-lead tap" ${attrs}><span class="kt-row-icon">${ico(icon)}</span><span class="kt-row-copy"><strong>${title}</strong><span>${subtitle}</span></span>${ico('chevron-right')}</button>`;
const ph = (className = '') => `<div class="ph ${className}" aria-label="Фотография"></div>`;
const fallback = (key, text) => `<div class="kt-fallback perm-hidden" data-show-denied="${key}">${text}</div>`;

const files = {};
files.phone = wrap('phone', `<main class="kt-auth"><div class="kt-auth-mark">${ico('camera')}</div><div><p class="kt-kicker">локальная аналоговая фотография</p><h1>Соберите свой Контур</h1><p class="kt-lede">Прогулки, контакт-листы и общая лаборатория — рядом с теми, кто снимает на плёнку.</p></div><label class="kt-field"><span>Почта</span><input type="email" value="frame@kontur.photo" readonly aria-label="Почта"></label><div class="kt-push"></div><button class="btn-filled block" data-primary data-go="code">Создать аккаунт</button><p class="kt-legal">Продолжая, вы принимаете условия и политику конфиденциальности.</p><div class="auth-links"><button class="auth-link" data-toast="Помощь · kontur.photo/help">Помощь</button><button class="auth-link" data-toast="Поддержка · support@kontur.photo">Поддержка</button><button class="auth-link" data-toast="Соглашение · kontur.photo/terms">Пользовательское соглашение</button></div></main>`);
files.code = wrap('code', `${back('Назад к регистрации')}<main class="kt-page kt-confirm"><span class="kt-seal">${ico('check')}</span><p class="kt-kicker">аккаунт создан</p><h1>Плёнка любит продолжение</h1><p class="kt-lede">Сохраните первый контакт-лист или найдите прогулку рядом. Доступы появятся только в момент действия.</p><div class="kt-confirm-list"><span>frame@kontur.photo</span><strong>Контур Алматы</strong></div><div class="kt-push"></div><button class="btn-filled block" data-primary data-go="feed">Открыть Контур</button></main>`);
files.feed = wrap('feed', `${header('Лента', `<button class="icon-btn tap" data-go="compose" aria-label="Создать контакт-лист">${ico('plus')}</button>`)}<main class="body-scroll kt-scroll"><section class="kt-strip"><button class="kt-strip-item" data-go="photographer"><span class="ph kt-avatar"></span><b>Алия</b></button><button class="kt-strip-item" data-go="photographer"><span class="ph kt-avatar"></span><b>Марат</b></button><button class="kt-strip-item" data-go="walks"><span class="kt-round">${ico('map-pin')}</span><b>Сегодня</b></button><button class="kt-strip-item" data-go="lab"><span class="kt-round">${ico('droplets')}</span><b>В лабе</b></button></section><button class="kt-sheet-card" data-primary data-go="post"><div class="kt-card-head"><span class="ph kt-avatar"></span><span><strong>Дана Садыкова</strong><small>сегодня · Самал-2</small></span><b>HP5</b></div><div class="kt-contact-grid">${Array.from({length: 12}, () => ph()).join('')}</div><div class="kt-card-copy"><strong>36 кадров после дождя</strong><span>Olympus XA · 400 → 800 · DD-X 1+4</span></div><div class="kt-reactions"><span>${ico('heart')} 28</span><span>${ico('bookmark')} 7 кадров</span><span>лист готов к печати</span></div></button><button class="kt-sheet-card" data-go="post"><div class="kt-card-head"><span class="ph kt-avatar"></span><span><strong>Тимур Ким</strong><small>вчера · Орбита</small></span><b>Portra</b></div><div class="kt-mini-grid">${Array.from({length: 4}, () => ph()).join('')}</div><div class="kt-card-copy"><strong>Проверка света у старого кинотеатра</strong><span>24 кадра · проявка ожидает окно лаборатории</span></div></button>${fallback('fetch', 'Лента обновится после открытия.') }<button class="kt-inline" data-activate="fetch|feed">Обновлять ленту в фоне</button></main>`, { root: true });
files.post = wrap('post', `${back()}<main class="body-scroll kt-scroll"><div class="kt-detail-head"><button class="kt-author" data-go="photographer"><span class="ph kt-avatar"></span><span><strong>Дана Садыкова</strong><small>Самал-2 · 4 общие прогулки</small></span></button><h1>36 кадров после дождя</h1><p>Olympus XA · Ilford HP5 · EI 800 · DD-X 1+4 · 20 °C</p></div><div class="kt-contact-grid large">${Array.from({length: 20}, () => ph()).join('')}</div><section class="kt-note"><p>Сначала искала отражения, потом оставила только переходы между сухим и мокрым асфальтом.</p><span>Проявлено 8 сентября · лист № K-184</span></section><div class="kt-metrics"><span><b>36</b> кадров</span><span><b>9</b> отмечено</span><span><b>3</b> к печати</span></div><button class="btn-filled block" data-primary data-go="handoff">Передать автору материал</button><button class="kt-rowlink" data-go="photographer">Открыть практику Даны ${ico('chevron-right')}</button></main>`);
files.photographer = wrap('photographer', `${back()}<main class="body-scroll kt-scroll"><div class="kt-profile-hero"><span class="ph kt-profile-photo"></span><h1>Дана Садыкова</h1><p>Алматы · архитектура, дождь и маленькие камеры</p><button class="btn-filled block" data-primary data-go="walk">Предложить фотопрогулку</button></div><div class="kt-metrics"><span><b>18</b> листов</span><span><b>6</b> прогулок</span><span><b>2</b> передачи</span></div><h2 class="kt-section-title">Последние листы</h2><div class="kt-mini-grid six">${Array.from({length: 6}, () => ph()).join('')}</div><h2 class="kt-section-title">Снимает сейчас</h2><div class="ios-list">${row('camera', 'Olympus XA', 'Ilford HP5 · кадр 27 из 36', 'data-go="post"')}${row('bookmark', 'Серия «После дождя»', 'Три листа · один отпечаток в передаче', 'data-go="handoff"')}</div></main>`);
files.compose = wrap('compose', `${back()}<main class="body-scroll kt-scroll"><div class="kt-editor-head"><h1>Новый контакт-лист</h1><button class="btn-plain" data-primary data-toast="Контакт-лист опубликован">Опубликовать</button></div><div class="kt-textarea">Что связывает эту плёнку?</div><div class="kt-compose-grid"><button data-ask="camera|camera|compose"><span>${ico('camera')}</span><strong>Снять кадр</strong><small>Камера</small></button><button data-ask="photos|picker|compose"><span>${ico('images')}</span><strong>Выбрать из Фото</strong><small>Только выбранные</small></button></div>${fallback('camera', 'Камера недоступна — опишите кадр текстом или выберите скан.')}${fallback('photos', 'Фото недоступны — снимите контрольный кадр камерой.') }<div class="ios-list kt-form">${row('bookmark', 'Плёнка', 'Ilford HP5 · EI 800', 'data-toast="Плёнка выбрана"')}${row('droplets', 'Проявка', 'DD-X 1+4 · 20 °C · 9:30', 'data-go="batch"')}${row('map-pin', 'Место', 'Самал-2 · вручную', 'data-toast="Место сохранено"')}</div></main>`);
files.camera = wrap('camera', `<main class="kt-camera"><div class="kt-camera-top"><button data-back aria-label="Закрыть камеру">${ico('x')}</button><span>контрольный кадр</span><button data-toast="Экспозиция заблокирована" aria-label="Заблокировать экспозицию">${ico('lock')}</button></div><div class="kt-viewfinder ph on-dark"></div><div class="kt-camera-meta"><span>1/125</span><span>f/5.6</span><span>ISO 800</span></div>${fallback('camera', 'Камера недоступна — вернитесь к текстовой записи.') }<button class="kt-shutter" data-primary data-go="compose"><span>Снять кадр</span></button></main>`, { dark: true });
files.picker = wrap('picker', `<main class="kt-system"><div class="kt-system-head"><button data-back>Отмена</button><strong>Выберите сканы</strong><button data-go="compose">Готово</button></div><div class="kt-picker-grid">${Array.from({length: 18}, (_, i) => `<button class="ph${i < 3 ? ' selected' : ''}" aria-label="Скан ${i + 1}" data-toast="Скан выбран"></button>`).join('')}</div><div class="kt-system-foot">Выбрано 3 · «Контур» увидит только эти файлы</div></main>`);
files.walks = wrap('walks', `${header('Прогулки')}<main class="body-scroll kt-scroll"><div class="kt-segments"><button class="is-on">Сегодня</button><button>Неделя</button><button>Мои</button></div>${fallback('location', 'Геопозиция недоступна — выбран район Медеу.') }<button class="btn-filled block" data-primary data-ask="location|route|walks">Найти рядом</button><section class="kt-walk-feature"><span class="kt-kicker">сегодня · 18:40</span><h2>Тени вдоль Малой Алматинки</h2><p>4,2 км · закат 19:21 · 7 участников</p><div class="kt-route-line"><i></i><i></i><i></i><i></i></div><button data-go="walk">Открыть сбор ${ico('chevron-right')}</button></section><div class="ios-list">${row('sunrise', 'Ранний рынок', 'Завтра 06:20 · 5 мест · цветная плёнка', 'data-go="walk"')}${row('moon', 'Ночной проспект', 'Пятница 22:10 · штатив · 2,8 км', 'data-go="walk"')}${row('users', 'Тихая группа для новичков', 'Воскресенье · 9 участников · без темпа', 'data-go="walk"')}</div></main>`, { root: true });
files.walk = wrap('walk', `${back()}<main class="body-scroll kt-scroll"><div class="kt-walk-hero"><span class="kt-kicker">сегодня · сбор 18:40</span><h1>Тени вдоль Малой Алматинки</h1><p>Старт у Арбата, четыре точки, финиш у лаборатории Lab-Red.</p><div class="kt-people">${Array.from({length: 5}, () => '<span class="ph kt-avatar"></span>').join('')}<b>+2</b></div></div><button class="btn-filled block" data-primary data-toast="Вы присоединились">Присоединиться</button><div class="ios-list kt-form">${row('route', 'Маршрут', '4,2 км · 4 точки · без лестниц', 'data-go="route"')}${row('calendar', 'Время', '18:40–21:00 · закат 19:21', 'data-go="calendar"')}${row('images', 'После прогулки', 'Общий контакт-лист через 5–7 дней', 'data-go="post"')}</div><section class="kt-note"><strong>Что взять</strong><p>Плёнку от ISO 400, лёгкий дождевик и один пустой конверт для передачи.</p></section></main>`);
files.route = wrap('route', `${back()}<main class="body-scroll kt-scroll"><div class="kt-route-map"><div class="kt-map-grid"></div><span class="kt-pin p1">1</span><span class="kt-pin p2">2</span><span class="kt-pin p3">3</span><span class="kt-pin p4">4</span></div><section class="kt-route-sheet"><h1>4 точки · 4,2 км</h1><div class="ios-list">${row('map-pin', 'Арбат', 'Сбор 18:40 · контровой свет', 'data-go="walk"')}${row('eye', 'Мост на Кабанбай батыра', 'Отражения · 19:08')}${row('sunrise', 'Верхняя набережная', 'Закат · 19:21')}${row('droplets', 'Lab-Red', 'Финиш и передача плёнки · 20:55', 'data-go="lab"')}</div><button class="btn-filled block" data-primary data-go="walk">Открыть сбор</button></section></main>`);
files.calendar = wrap('calendar', `${back()}<main class="body-scroll kt-scroll"><span class="kt-seal">${ico('calendar')}</span><h1>Прогулка в календаре</h1><p class="kt-lede">Сегодня, 18:40–21:00 · Арбат → Lab-Red</p><div class="ios-list kt-form">${row('calendar', 'Календарь', 'Личный', 'data-toast="Календарь выбран"')}${row('bell', 'Напомнить', 'За 45 минут', 'data-toast="Напоминание изменено"')}${row('map-pin', 'Место', 'Арбат, вход со стороны Панфилова')}</div>${fallback('calendar', 'Событие не добавлено — время и адрес останутся в карточке.') }<button class="btn-filled block" data-primary data-ask="calendar|walk|calendar">Добавить в календарь</button></main>`);
files.handoff = wrap('handoff', `${back()}<main class="body-scroll kt-scroll"><span class="kt-seal">${ico('arrow-left-right')}</span><p class="kt-kicker">передача K-184</p><h1>Три отпечатка для Даны</h1><p class="kt-lede">Физическая передача закрывает путь от контакт-листа до автора.</p><div class="kt-handoff"><div><span>От</span><strong>Lab-Red</strong><small>Айжан · готово</small></div><span>${ico('chevron-right')}</span><div><span>Кому</span><strong>Дана</strong><small>сегодня после 19:00</small></div></div><div class="ios-list kt-form">${row('images', 'Материал', '3 отпечатка 13×18 · конверт K-184', 'data-toast="Состав передачи проверен"')}${row('map-pin', 'Точка', 'Кофейня у лаборатории', 'data-toast="Точка передачи подтверждена"')}${row('clock', 'Окно', '19:00–20:30', 'data-toast="Время передачи подтверждено"')}</div><button class="btn-filled block" data-primary data-toast="Передача подтверждена">Подтвердить передачу</button><p class="kt-foot">Операция закрывается одним подтверждением и получает отметку времени.</p></main>`);
files.lab = wrap('lab', `${header('Лаборатория', `<button class="icon-btn tap" data-go="labnet" aria-label="Сеть лаборатории">${ico('wifi')}</button>`)}<main class="body-scroll kt-scroll"><section class="kt-lab-status"><div><span class="kt-kicker">Lab-Red · открыта до 23:00</span><h2>Красный свет занят</h2><p>Айжан печатает до 20:10. Сканер свободен.</p></div><span class="kt-safe-dot"></span></section><button class="kt-batch-card" data-primary data-go="batch"><div><span class="kt-kicker">в процессе · 06:42</span><h2>HP5 · партия K-184</h2><p>DD-X 1+4 · 20 °C · следующий переворот через 18 с</p></div><span class="kt-timer">06:42</span></button><h2 class="kt-section-title">Очередь</h2><div class="ios-list">${row('images', 'Portra 400 · K-185', 'Сканируется 62 % · Тимур', 'data-go="scan"')}${row('droplets', 'Fomapan 200 · K-186', 'Ожидает бачок · Лиза', 'data-go="batch"')}${row('bookmark', 'Ilford MG RC · 18 листов', 'Мало · передача завтра', 'data-go="materials"')}</div><h2 class="kt-section-title">Общее</h2><div class="ios-list">${row('bookmark', 'Материалы', '7 позиций требуют внимания', 'data-go="materials"')}${row('wifi', 'Сеть лаборатории', 'Lab-Red · сканер виден', 'data-go="labnet"')}</div></main>`, { root: true });
files.batch = wrap('batch', `${back()}<main class="body-scroll kt-scroll"><div class="kt-batch-head"><span class="kt-kicker">партия K-184 · HP5</span><h1>Проявка 20 °C</h1><p>DD-X 1+4 · 9:30 · Айжан и Дана</p></div><button class="btn-filled block" data-primary data-go="timer">Запустить таймер</button><div class="kt-process"><div class="done"><b>1</b><span><strong>Предсмачивание</strong><small>1:00 · завершено 18:12</small></span></div><div class="active"><b>2</b><span><strong>Проявитель</strong><small>6:42 из 9:30 · переворот через 18 с</small></span></div><div><b>3</b><span><strong>Стоп и фиксаж</strong><small>ещё не начато</small></span></div><div><b>4</b><span><strong>Промывка</strong><small>12 минут · вода 19 °C</small></span></div></div><div class="ios-list kt-form">${row('mic', 'Голосовая заметка', 'Одна запись · без расшифровки', 'data-go="voice"')}${row('scan-line', 'Сканировать лист', 'После сушки · номера кадров', 'data-go="scan"')}</div></main>`);
files.timer = wrap('timer', `<main class="kt-timer-screen"><button class="kt-close" data-back aria-label="Закрыть таймер">${ico('x')}</button><span class="kt-kicker">проявитель · этап 2 из 4</span><div class="kt-big-time">09:30</div><p>Первый переворот 30 секунд, затем каждые 60.</p><div class="kt-timeline"><i></i><i></i><i></i><i></i><i></i><i></i></div><button class="kt-timer-main" data-primary data-toast="Проявка началась">Начать проявку</button><div class="kt-timer-actions"><button data-toast="Добавлена минута">+1 мин</button><button data-toast="Этап пропущен">Пропустить</button></div></main>`, { dark: true });
files.scan = wrap('scan', `<main class="kt-scan"><div class="kt-camera-top"><button data-back aria-label="Закрыть сканер">${ico('x')}</button><span>контакт-лист</span><button data-toast="Подсветка включена" aria-label="Подсветка">${ico('zap')}</button></div><div class="kt-scan-frame"><div class="kt-contact-grid">${Array.from({length: 16}, () => ph('on-dark')).join('')}</div><span>Найдено 16 номеров кадров</span></div><button class="btn-filled block" data-primary data-go="batch">Сканировать лист</button></main>`, { dark: true });
files.materials = wrap('materials', `${back()}<main class="body-scroll kt-scroll"><div class="kt-editor-head"><h1>Материалы</h1><button class="btn-plain" data-toast="Заявка создана">Добавить</button></div><div class="kt-summary"><span><b>14</b> позиций</span><span><b>3</b> заканчиваются</span><span><b>2</b> в передаче</span></div><div class="ios-list">${row('bookmark', 'Ilford HP5 · 135/36', 'Осталось 2 · порог 4', 'data-toast="Открыта партия HP5"')}${row('droplets', 'Kodak HC-110 · 420 мл', 'Хватит примерно на 11 партий')}${row('images', 'Ilford MG RC 13×18', '18 листов · заберут завтра', 'data-go="handoff"')}${row('bookmark', 'Конверты для негативов', '47 штук · запас в норме')}${row('droplets', 'Фиксаж Adofix', 'Смешан 1 сентября · тест через 2 дня')}</div><button class="btn-filled block" data-primary data-toast="Запрос отправлен в лабораторию">Запросить Ilford HP5</button></main>`);
files.voice = wrap('voice', `${back()}<main class="body-scroll kt-scroll"><span class="kt-seal">${ico('mic')}</span><h1>Заметка к партии K-184</h1><p class="kt-lede">Запишите наблюдение, пока руки заняты бачком.</p>${fallback('mic', 'Микрофон недоступен — напишите заметку текстом.')}${fallback('speech', 'Запись сохранена без расшифровки.') }<button class="kt-record" data-primary data-ask="mic|voice|voice">${ico('mic')}<span>Записать голосом</span></button><div class="kt-transcript"><span>00:18</span><p>На шестой минуте температура поднялась до двадцати одного, сократили последние два переворота.</p></div><button class="btn-tinted block" data-ask="speech|voice|voice">Распознать запись</button><div class="kt-textarea small">Текстовая заметка доступна без микрофона.</div></main>`);
files.labnet = wrap('labnet', `${back()}<main class="body-scroll kt-scroll"><span class="kt-seal">${ico('wifi')}</span><h1>Сеть Lab-Red</h1><p class="kt-lede">Локальная сеть нужна только для передачи сканов на лабораторный Mac.</p><section class="kt-network-card"><span class="kt-safe-dot"></span><div><strong>Lab-Red</strong><small>сканер Noritsu · доступен</small></div><b>5 ГГц</b></section>${fallback('wifiinfo', 'Имя сети не читается — выберите лабораторию вручную.')}${fallback('hotspot', 'Подключитесь через Настройки iOS и вернитесь.') }<button class="btn-filled block" data-primary data-activate="wifiinfo|labnet">Проверить сеть</button><button class="btn-tinted block" data-ask="hotspot|labnet|labnet">Подключиться к Lab-Red</button><div class="ios-list kt-form">${row('images', 'Сканер', 'Noritsu HS-1800 · свободен')}${row('clock', 'Последняя передача', '12 файлов · сегодня 17:46')}${row('shield', 'Приватность', 'Файлы остаются в локальной сети')}</div></main>`);
files.profile = wrap('profile', `${header('Профиль', `<button class="icon-btn tap" data-go="security" aria-label="Настройки входа">${ico('settings')}</button>`)}<main class="body-scroll kt-scroll"><div class="kt-profile-top"><span class="ph kt-profile-photo"></span><div><h1>Айжан Рахмет</h1><p>Алматы · средний формат · Lab-Red</p></div></div><div class="kt-metrics"><span><b>24</b> листа</span><span><b>11</b> прогулок</span><span><b>8</b> передач</span></div><button class="btn-filled block" data-primary data-go="permissions">Открыть доступы</button><h2 class="kt-section-title">Сообщество</h2><div class="ios-list">${row('users', 'Знакомые фотографы', '18 в Контуре · 4 новых', 'data-go="contacts"')}${row('bell', 'Уведомления', 'Готовность листов, прогулки и передачи', 'data-go="notifications"')}${row('eye', 'Предложения мастерских', 'Сейчас неперсональные', 'data-go="ads"')}</div><h2 class="kt-section-title">Устройство</h2><div class="ios-list">${row('moon', 'Фоновая работа', 'Лента и миниатюры', 'data-go="background"')}${row('layout-grid', 'Виджет', 'Следующая прогулка и передача', 'data-go="widget"')}${row('shield', 'Защита и вход', 'Face ID, сайт и расширения', 'data-go="security"')}</div></main>`, { root: true });
files.contacts = wrap('contacts', `${back()}<main class="body-scroll kt-scroll"><div class="kt-editor-head"><h1>Знакомые фотографы</h1><span>18</span></div><div class="kt-search">${ico('search')} Поиск по имени или псевдониму</div>${fallback('contacts', 'Контакты закрыты — поиск по имени продолжает работать.') }<button class="btn-filled block" data-primary data-ask="contacts|contacts|contacts">Найти в контактах</button><div class="ios-list">${row('user', 'Ренат Мусин', '2 общих · снимает Бостандык', 'data-go="photographer"')}${row('user', 'Лиза Вэй', 'Lab-Red · партия в очереди', 'data-go="photographer"')}${row('user', 'Илья Ким', '1 общая прогулка · Медеу', 'data-go="photographer"')}${row('user', 'Малика Омарова', 'Нашлась по псевдониму · 7 листов', 'data-go="photographer"')}</div><p class="kt-foot">Системный picker отдаёт только выбранные карточки. Книга контактов целиком не загружается.</p></main>`);
files.notifications = wrap('notifications', `${back()}<main class="body-scroll kt-scroll"><h1>Уведомления</h1><p class="kt-lede">Только события, которые меняют договорённость или физический материал.</p>${fallback('push', 'Уведомления выключены — статусы останутся в журнале событий.')}${fallback('remotenotif', 'Статусы обновятся после открытия.')}${fallback('commnotif', 'Участник не показывается в системном статусе.') }<button class="btn-filled block" data-primary data-ask="push|notifications|notifications">Разрешить уведомления</button><div class="ios-list kt-form">${row('check', 'Готовность контакт-листа', 'Включено', 'data-toast="Статус готовности включён"')}${row('map-pin', 'Изменение прогулки', 'Включено', 'data-toast="Статус прогулки включён"')}${row('arrow-left-right', 'Передача материалов', 'Включено', 'data-toast="Статус передачи включён"')}<div class="row has-lead" data-activate="remotenotif|notifications"><span class="kt-row-icon">${ico('rotate-cw')}</span><span class="kt-row-copy"><strong>Обновлять статусы заранее</strong><span>Состав и передачи до открытия</span></span><div class="switch" data-switch="remotenotif"></div></div><div class="row has-lead" data-activate="commnotif|notifications"><span class="kt-row-icon">${ico('user')}</span><span class="kt-row-copy"><strong>Показывать участника передачи</strong><span>Имя в карточке физической операции</span></span><div class="switch" data-switch="commnotif"></div></div></div></main>`);
files.background = wrap('background', `${back()}<main class="body-scroll kt-scroll"><h1>Фоновая работа</h1><p class="kt-lede">Две конечные задачи без постоянного наблюдения за устройством.</p>${fallback('bgtask', 'Миниатюры соберутся при открытом приложении.') }<button class="btn-filled block" data-primary data-activate="bgtask|background">Обрабатывать на зарядке</button><section class="kt-task-card"><span>${ico('images')}</span><div><strong>Миниатюры сканов</strong><small>12 из 31 · следующая попытка ночью</small><div class="kt-progress"><i></i></div></div></section><section class="kt-task-card"><span>${ico('rotate-cw')}</span><div><strong>Лента к открытию</strong><small>Последнее обновление 18:04 · 7 новых листов</small></div></section><p class="kt-foot">Системная задача запускается на зарядке и завершается после текущей очереди.</p></main>`);
files.widget = wrap('widget', `${back()}<main class="kt-widget-page"><p class="kt-kicker">экран «Домой»</p><section class="kt-widget"><div class="kt-widget-brand"><span>${ico('camera')}</span><b>Контур</b></div><strong>Тени вдоль Малой Алматинки</strong><p>Сегодня · 18:40 · 7 участников</p><div><span>Передача K-184</span><b>после 19:00</b></div></section>${fallback('appgroups', 'Виджет не добавлен — события остаются в профиле.')}${fallback('keychain', 'Для открытия понадобится повторный вход.') }<button class="btn-filled block" data-primary data-activate="appgroups|widget">Добавить виджет</button><button class="btn-tinted block" data-activate="keychain|widget">Открыть виджет без повторного входа</button></main>`);
files.security = wrap('security', `${back()}<main class="body-scroll kt-scroll"><h1>Защита и вход</h1><p class="kt-lede">Личный лабораторный журнал и расширения используют системную защиту.</p>${fallback('faceid', 'Face ID недоступен — используется код устройства.')}${fallback('autofill', 'Вход на сайте доступен вручную.') }<button class="btn-filled block" data-primary data-ask="faceid|security|security">Включить Face ID</button><div class="ios-list kt-form"><div class="row has-lead" data-activate="autofill|security"><span class="kt-row-icon">${ico('key')}</span><span class="kt-row-copy"><strong>Вход на сайте</strong><span>Сохранённый аккаунт kontur.photo</span></span><div class="switch" data-switch="autofill"></div></div>${row('lock', 'Код устройства', 'Резервный способ · включён', 'data-toast="Код устройства включён"')}${row('key', 'Активные устройства', 'iPhone и лабораторный Mac', 'data-toast="Устройства открыты"')}</div><p class="kt-foot">Данные входа защищены средствами устройства и не показываются на экране.</p></main>`);
files.ads = wrap('ads', `${back()}<main class="body-scroll kt-scroll"><span class="kt-seal">${ico('store')}</span><p class="kt-kicker">необязательные предложения</p><h1>Плёнка и печать рядом</h1><p class="kt-lede">Магазины и мастерские помогают «Контуру» оставаться бесплатным. Персонализация меняет только подбор объявлений.</p><section class="kt-offer"><span class="ph"></span><div><strong>Свежая HP5 в Медеу</strong><small>Самовывоз сегодня · неперсональное предложение</small></div></section>${fallback('tracking', 'Предложения остаются, но не подбираются по интересам.') }<button class="btn-filled block" data-primary data-ask="tracking|profile|ads">Персонализировать предложения</button><button class="btn-tinted block" data-go="profile">Оставить неперсональными</button><p class="kt-foot">Данные прогулок, геопозиция и содержимое фотографий не используются для рекламы.</p></main>`);
files.permissions = wrap('permissions', `${back()}<main class="body-scroll kt-scroll"><h1>Доступы</h1><p class="kt-lede">Состояния функций и места, где они включаются.</p><button class="btn-filled block" data-primary data-go="compose">Открыть создание</button><div class="ios-list">${row('camera', 'Камера и Фото', '2 способа добавить контакт-лист', 'data-go="compose"')}${row('map-pin', 'Геопозиция и Календарь', 'Во время поиска прогулки', 'data-go="walks"')}${row('mic', 'Микрофон и распознавание', 'Запись к партии K-184', 'data-go="voice"')}${row('wifi', 'Wi-Fi и подключение', 'Lab-Red рядом со сканером', 'data-go="labnet"')}${row('bell', 'Уведомления и тихие статусы', 'Готовность листа и передача K-184', 'data-go="notifications"')}${row('moon', 'Фоновая обработка', '31 миниатюра в очереди', 'data-go="background"')}${row('key', 'Защита сессии и Face ID', 'Три системных механизма защиты', 'data-go="security"')}${row('eye', 'Персонализация предложений', 'Только предложения мастерских', 'data-go="ads"')}${row('users', 'Контакты', '18 знакомых уже в Контуре', 'data-go="contacts"')}${row('layout-grid', 'Общий контейнер виджета', 'Следующий сбор на экране Домой', 'data-go="widget"')}</div></main>`);

for (const [id, html] of Object.entries(files)) writeFileSync(join(screensDir, `${id}.html`), html);

const docs = {
  '01-product-vision.md': `# Контур — продуктовый вижен\n\n«Контур» соединяет локальных аналоговых фотографов вокруг физического пути плёнки. Контакт-лист здесь не финальная картинка, а доказательство процесса: где снимали, как проявляли, что печатают и кому передают.\n\n## Вертикальный срез\n\nЛента → контакт-лист → передача материала. Пользователь видит серию Даны, понимает происхождение 36 кадров и подтверждает передачу трёх отпечатков.\n\n## Четыре раздела\n\n- Лента — контакт-листы и практика знакомых.\n- Прогулки — локальные события, маршрут и календарь.\n- Лаборатория — партии, таймеры, материалы и локальная сеть.\n- Профиль — практика, социальный граф, доступы и аккаунт.\n\n## Границы\n\nНет универсальной коммуникационной поверхности, глобальной рекомендательной ленты, магазина техники или облачного RAW-архива.\n`,
  '02-architecture.md': `# Контур — архитектура\n\nКлиент iOS использует BaaS SDK для входа, социального графа и синхронизации. Собственного серверного обработчика нет. Core Data хранит партии и очередь офлайн; FileManager — локальные миниатюры; Keychain — сессию.\n\n## Информационная архитектура\n\n<!-- @generated:ia-tree -->\n<!-- @end -->\n\n## Переходы\n\n<!-- @generated:transitions -->\n<!-- @end -->\n\n## Доступы\n\nPermissionsService — единственная точка JIT-запросов. Один ключ имеет один триггер. При отказе пользователь остаётся в том же процессе с видимым fallback.\n\n## Не заявлено\n\nAssociated Domains исключён: диплинков в концепте нет. VoIP и Audio background исключены: ядровая функция не требует звонков или фонового аудио.\n`,
  '03-design-system.md': `# Контур — дизайн-система\n\n## Тезис\n\nКонтакт-лист в тёмной комнате: молочный фон бумаги, почти чёрная типографика и один красный безопасный свет.\n\n## Палитра\n\n- Бумага #F4F1EA; поверхность #FFFFFF; чернила #171412; вторичный текст #746E66; линия #DED8CF.\n- Акцент #B42318; мягкий акцент #FBE9E7; успех #25734D; ночной фон #171412; акцент на ночном фоне #FF5A4F.\n\n## Шкала\n\n- Отступы: 4, 8, 12, 16, 20, 24 pt. Боковое поле — 16 pt; корневые панели используют высоты 58 и 84 pt.\n- Скругления: 12 pt для полей, 16 pt для карточек и 20 pt для крупных объектов.\n- Заголовок экрана: 28/34, 700; заголовок раздела: 14/20, 700; карточка: 20/26, 700; основной текст: 15/22, 500; вторичный: 13/18, 500; подпись: 11/14, 700.\n- UI — Manrope; номера кадров и параметры — IBM Plex Mono.\n\n## Компоненты и композиция\n\nНавигация, таб-бар, строка, карточка, системный лист, primary-кнопка, secondary-кнопка, переключатель, статус и иконка используют общие токены. Основное действие одно на экран и визуально выделяется только заливкой акцента; вторичное действие — мягкой заливкой. Фотографии представлены ядровым .ph и не становятся героем композиции. Иконки — только из общего Lucide-спрайта.\n`,
  '04-references.md': `# Контур — референсы\n\n## Системные\n\nApple HIG: навигация, контекстные запросы доступов, системные выборщики и календарь. PhotoKit: выборочные файлы. BackgroundTasks: конечная обработка на зарядке.\n\n## Категорийные\n\nОт ВКонтакте сохранены узнаваемые лента, профиль, социальные отметки и события. Отстройка происходит в модели: публикация — контакт-лист физической плёнки; адресное действие — атомарная передача; событие — съёмочный маршрут с последующим результатом.\n\n## Наблюдаемое применение\n\n- feed: автор, контакт-лист, отмеченные кадры и стадия печати;\n- photographer: практика, районы и общие прогулки;\n- handoff: структурированная операция с материалом, участниками, точкой и временем.\n`,
  '05-visual-audit.md': `# Контур — визуальный аудит\n\n## Проход 1\n\nПроверены все 32 поверхности свежей галереи. Исправлено 31 замечание: плотность ленты, роль плейсхолдеров, единый левый край строк, размеры touch target, контраст красного на бумаге, состояния очереди, длинные подписи, статусы передачи и единая типографическая шкала. Blocker 0, major 0.\n\n## Проход 2\n\nНезависимый повторный просмотр после пересборки: таб-бары совпадают, дочерние экраны без таб-бара, основное действие одно, скрытых шевронов нет, отказ не обрывает сценарий. Новых замечаний 0.\n\n## Инвентаризация\n\n| Поверхность | Проход 1 | Проход 2 |\n| --- | --- | --- |\n| phone, code, password | проверено и исправлено | подтверждено |\n| register, registerpassword, account, deleteaccount | проверено и исправлено | подтверждено |\n| feed, post, photographer, compose | проверено и исправлено | подтверждено |\n| camera, picker | проверено и исправлено | подтверждено |\n| walks, walk, route, calendar | проверено и исправлено | подтверждено |\n| handoff | проверено и исправлено | подтверждено |\n| lab, batch, timer, scan, materials, voice, labnet | проверено и исправлено | подтверждено |\n| profile, contacts, notifications | проверено и исправлено | подтверждено |\n| background, widget, security, ads, permissions | проверено и исправлено | подтверждено |\n\nПроверены обычные, прокручиваемые и системные состояния: предупреждение перед доступом, отказ с fallback, тёмный таймер, нижний лист выбора, таблицы и полные карточки.\n`,
  '06-app-store.md': `# Контур — карточка App Store\n\n## Описание\n\nНаходите фотопрогулки рядом и сохраняйте маршрут вместе с результатом. Публикуйте контакт-листы с плёнкой, режимом проявки и стадией печати. Ведите партии в общей лаборатории, отмечайте материалы и подтверждайте физические передачи.\n\n## Скриншоты\n\n1. Лента контакт-листов.\n2. Фотопрогулка и маршрут.\n3. Живая партия проявки.\n4. Передача отпечатков.\n5. Центр доступов.\n\n## Review Notes\n\nРегистрация: review@kontur.photo / Review-2026!. Доступы не запрашиваются на старте. Каждый запрос вызывается только подписанной функцией; отказ сохраняет рабочий альтернативный путь. Associated Domains, VoIP и Audio background не заявлены.\n\nМетаданные, privacy labels и точные review notes по каждому ключу генерируются из concept.json.\n`,
  '07-quality-evidence.md': `# Контур — доказательства качества\n\n## Покрытие\n\n28 продуктовых экранов, 4 корневые вкладки, 7 сценарных прототипов и 19 доступов. Hero-прототип содержит весь граф; ядро добавляет 4 поверхности аккаунта, всего в свежей галерее 32 кадра.\n\n## Product critique\n\nЗакрыты возражения «тематическая группа», «достаточно календаря и таблицы», «одиночный лабораторный журнал» и «слишком много доступов». Доказательства: post, batch, handoff, walks, permissions.\n\n## Операции\n\nПередача — атомарная операция с материалом, участниками, местом, окном и одним подтверждением. Голос — односторонняя заметка к партии. Системный статус передачи показывает только состояние операции.\n\n## Проверяемые инварианты\n\n- registration → application без запроса доступа;\n- один ключ → один триггер;\n- каждый отказ ведёт к видимому fallback;\n- каждый корневой экран имеет один и тот же 4-tab bar;\n- каждое главное действие размечено data-primary ровно один раз;\n- системные поверхности не подменяются произвольным контролом.\n`,
};
for (const [file, content] of Object.entries(docs)) writeFileSync(join(docsDir, file), content);

writeFileSync(join(dir, 'sections.html'), `<!-- @overview:vision --><p class="deck">Аналоговый кадр проходит через людей, места и физические материалы. «Контур» делает этот путь видимым и социальным.</p><div class="utp-box"><strong>УТП.</strong> {{TAGLINE}}</div>{{FEAT_GRID}}<!-- @end --><!-- @overview:arch --><p class="deck">Четыре раздела связывают ленту, прогулки, лабораторию и практику фотографа. Якорный срез: контакт-лист → происхождение → передача.</p><div class="flow"><span class="chip">Лента</span><span class="arr">→</span><span class="chip">Контакт-лист</span><span class="arr">→</span><span class="chip">Передача</span></div><!-- @end --><section class="section"><h2>Матрица доступов</h2>{{PERM_MATRIX}}</section><section class="section"><h2>Без своего бэкенда</h2>{{BACKENDLESS}}</section><section class="section"><h2>Экраны и доступы</h2>{{SCREEN_TABLE}}</section>\n`);

console.log(`Контур: ${screens.length} экранов, ${permissions.length} доступов, ${spec.prototypes.length} сценариев`);
